### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by pangyunxiu** [LikeRainDay/ASO_demo#4]
作者你好，我们想弄自己的 ASO 给自己的 APP 进行机刷打榜，能加个QQ 详聊吗：116914885

**Comment by RainLib** [comment]
> 作者你好，我们想弄自己的 ASO 给自己的 APP 进行机刷打榜，能加个QQ 详聊吗：116914885

不好意思呀，已经很久不做这方面了。

**Comment by pangyunxiu** [comment]
我愿意给一定的技术咨询费哦

**Comment by RainLib** [comment]
> 我愿意给一定的技术咨询费哦

不好意思，暂时不感兴趣。 目前在其他方向，这个已经4年没专研了，最新的业界迭代不太清楚了。
